<!-- application/layouts/scripts/layout.phtml -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" class="nojs">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Frontend Test</title>
	<?php echo $this->headLink()->appendStylesheet('css/styles.css') ?>
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.5/jquery.bxslider.min.js"></script>
	
	<?php echo $this->headScript()->appendFile('js/scripts.js') ?>
</head>
<body>
	<?php echo $this->render('header.phtml') ?>
	<?php echo $this->layout()->content ?>
	<?php echo $this->render('footer.phtml') ?>
</body>
</html>