<!-- application/views/scripts/index/index.phtml -->
<main class="main-content">
	<section class="gallery">
		<h1>Gallery of products</h1>
			<ul>
				<li><a href="">
						<figure>
							<img src="http://placehold.it/940x302" alt="Pic 1">
							<figcaption>Figcaption 1</figcaption>
						</figure>
					</a></li>
				<li><a href="">
						<figure>
							<img src="http://placehold.it/940x302" alt="Pic 2">
							<figcaption>Figcaption 2</figcaption>
						</figure>
					</a></li>
				<li><a href="">
						<figure>
							<img src="http://placehold.it/940x302" alt="Pic 3">
							<figcaption>Figcaption 3</figcaption>
						</figure>
					</a></li>
			</ul>
	</section>

	<section class="favorites">
		<h1>Our Favourites</h1>
		<ul>
			<?php 
			$products = $this->products();
			$products_titles = array();
			for ($i = 1; $i <= 3; $i++) {
				foreach ($products as $k => $v) {
				    $products_titles[$k] = $v['title'];
				}
				array_multisort($products_titles, SORT_ASC, $products);
				foreach ($products as $product) {
					echo "<li><figure>";
						echo "<a class=\"product_image_link\" href=\"?productinfo\"><img src=\"".$product['image']."\" alt=\"".$product['title']."\"></a>";
						echo "<figcaption><a href=\"?productinfo\" class=\"product_title\">".$product['title']."</a>";
						echo "<div class=\"product_price\">";
						if ($product['special_price']) {
							echo "<s>&euro; ".$product['price']."</s> <span class=\"new_price\">&euro; ".$product['special_price']."</span>";
						} else {
							echo "&euro; ".$product['price'];
						}
						echo "</div><a href=\"?addtocart\" class=\"button\">Add to cart</a></figcaption>";
					echo "</figure></li>";
				}
			}
			?>
		</ul>
	</section>

	<section class="tabs">
		<h1>Information on sizes</h1>
	</section>

	<article class="store_desc">
		<h1 class="heading-medium">This is our new store</h1>
		<div class="text">Curabitur est justo, tincidunt sit amet dignissim suscipit, sodales at odio. Sed hendrerit elit malesuada tristique fermentum. Nam sed ultricies leo, ac fermentum nisi. Etiam quis dolor vel arcu scelerisque eleifend. Donec placerat aliquam lacus, quis vulputate urna lobortis in. Sed eu nisi eu arcu adipiscing laoreet. Sed pharetra urna vel purus aliquet hendrerit. Duis vel velit vitae odio tempus ultricies. Praesent ullamcorper bibendum elit, sollicitudin pulvinar risus consequat ac. Donec a porttitor nibh, ac pretium velit. Quisque quis leo venenatis, aliquet urna sed, gravida dui. Sed imperdiet aliquam dolor quis dignissim.
Mauris ornare venenatis magna, vel commodo velit vestibulum ac. Praesent iaculis, neque vel ultricies posuere, enim risus posuere nisl, a rhoncus massa lorem sit amet tortor. Cras molestie turpis quis sem elementum, in ultricies ante iaculis. Morbi blandit tempor varius. Nullam vel adipiscing mauris. Suspendisse ante tortor, gravida id risus consectetur, cursus aliquam nibh. Nullam vulputate, nibh vitae vehicula viverra, lorem quam tincidunt justo, ut consectetur metus turpis sed ante. Praesent nec faucibus augue, at ornare elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus venenatis, orci sit amet viverra sagittis, nisi lacus ullamcorper ante, vitae viverra magna ligula et sem.</div>

	</article>
</main>