<!-- application/views/scripts/footer.phtml-->
<footer class="page-footer">
	<div class="page-footer_inner">
		<div class="newsletter">
			<h2>Newsletter subscribe</h2>
			<form action="/newsletter/subscribe" method="GET" class="newsletter-form">
				<input type="text" id="newsletter-email" name="email" placeholder="firstname.lastname@company.com">
				<input type="submit" value="Subscribe" class="button" id="newsletter-submit">
			</form>
		</div>

		<nav class="footer-nav">
			<ul>
				<li>
					<section>
						<h1>Top categories</h1>
						<ul>
							<li><a href="">Women</a></li>
							<li><a href="">Men</a></li>
							<li><a href="">Junior</a></li>
							<li><a href="">Accessories</a></li>
						</ul>
					</section>
				</li>
				<li>
					<section>
						<h1>Customer service</h1>
						<ul>
							<li><a href="">Returns</a></li>
							<li><a href="">Shipping</a></li>
							<li><a href="">About us</a></li>
							<li><a href="">Contact us</a></li>
						</ul>
					</section>
				</li>
			</ul>
		</nav>
	</div>
</footer>